#!/bin/ksh
# Replace the <> stuff with your own content
# the export is required for your environment in order to cron to detect it in the background
# best practice is to create a user BackupDb , grant the necessary privilege and allow that to use the datapump

export ORACLE_SID=<Instance_Name>
export ORACLE_HOME=<DbHome Installation>
export PATH=$PATH:$ORACLE_HOME/bin
export currentDate=`date +%d%m%y_%H%M%S`
export systemLogin="<export_user>/<Password>"
export dbName=<DbName>

if echo "exit;" | sqlplus ${systemLogin}@${dbName} 2>&1 | grep -q "Connected to"
then

sqlplus ${systemLogin} as sysdba <<eof
# if cdb alter session set container=<dbName>;
create or replace directory DBPUMP as '<Location of Backup>';
grant read, write on directory DBPUMP to public;
exit;
eof

# Start the expdp command
cd <Backup_Location>

if [ -e Log_${dbName}_* ] then
 rm Log_$dbName_*.log
fi

expdp ${systemLogin}@${dbName} directory=DBPUMP dumpfile=${dbName}_$currentDate.dmp full=y compression=all logfile=Log_${dbName}_$currentDate.log

rm *${ORACLE_SID}_*.gz
gzip -9 ${dbName}_$currentDate.dmp

else
    echo "Connection FAIL"
fi

